_extends: brianespinosa/settings:base.yml

repository:
  name: shippo-packing-slips
  description: Raspberry Pi Zero scripts to generate custom packing slips and print them and any new shipping labels at regular intervals using Shippo API
  topics: raspberry-pi-zero-2-w, shippo
  private: false
