_extends: brianespinosa/settings:base.yml

repository:
  name: shippo-packing-slips
  description: Raspberry Pi scripts to print packing slips, shipping labels, and schedule USPS pickups at regular intervals using the Shippo API
  topics: nodejs,raspberry-pi,shippo,shipping,typescript
  private: false
